apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-okonomi-kodeverk
  namespace: tromsfylke-no
spec:
  url:
    hostname: api.felleskomponent.no
  ingress:
    basePaths:
      - /okonomi/kodeverk
    headers:
      x-org-id: tromsfylke.no
  kafka:
    enabled: true
    acls:
      - topic: 'tromsfylke-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"