apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-utdanning-ot
  namespace: viken-no
spec:
  url:
    hostname: api.felleskomponent.no
  ingress:
    basePaths:
      - /utdanning/ot
    headers:
      x-org-id: viken.no
  kafka:
    enabled: true
    acls:
      - topic: 'viken-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"