apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-utdanning-utdanningsprogram
  namespace: sdworx-com
spec:
  url:
    hostname: beta.felleskomponent.no
  ingress:
    basePaths:
      - /utdanning/utdanningsprogram
    headers:
      x-org-id: sdworx.com
  kafka:
    enabled: true
    acls:
      - topic: 'sdworx-com.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"