apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-arkiv-samferdsel
  namespace: innlandetfylke-no
spec:
  url:
    hostname: alpha.felleskomponent.no
  ingress:
    basePaths:
      - /arkiv/samferdsel
    headers:
      x-org-id: innlandetfylke.no
  kafka:
    enabled: true
    acls:
      - topic: 'innlandetfylke-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"