fint:
  kafka:
    consumers:
      resource:
        seek-to-beginning: true
        concurrency: 6
      auto-relation-resource:
        seek-to-beginning: false
        concurrency: 6
      relation-update:
        seek-to-beginning: true
        concurrency: 6
      event:
        seek-to-beginning: true
        concurrency: 1
  security:
    opa:
      enabled: false
    exposed-endpoints:
      - /actuator/prometheus
      - /actuator/health
  relation:
    base-url: https://api.felleskomponent.no
  consumer:
    pod-url: http://fint-core-consumer-${fint.consumer.domain}-${fint.consumer.package}:8080
    base-url: ${fint.relation.base-url}
    domain: utdanning
    package: vurdering
    packageName: ${fint.consumer.package}
    org-id: ${fint.org-id}
    coreVersionHeader: 2

novari:
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: fint-core
    application-id: fint-core-consumer-${fint.consumer.domain}-${fint.consumer.package}-${fint.org-id}

spring:
  threads:
    virtual:
      enabled: true
  webflux:
    base-path: ${fint.consumer.domain}/${fint.consumer.package}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${novari.kafka.application-id}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health

logging:
  level:
      org.apache.kafka: WARN
      no.novari.kafka: WARN
