package no.fintlabs.consumer.integration

import no.fintlabs.Application
import no.novari.fint.model.FintMultiplicity
import no.novari.fint.model.FintRelation
import no.novari.metamodel.MetamodelService
import no.novari.metamodel.model.Resource
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.kafka.test.context.EmbeddedKafka
import org.springframework.test.annotation.DirtiesContext
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.TestPropertySource
import java.io.File

/**
 * Scans the FINT metamodel for relation pairs where two resources reference each
 * other (each side has a relation whose `packageName` resolves to the other class)
 * but at least one side is missing `inverseName`.
 *
 * Pure 1-to-1 pairs are excluded because the auto-relation pipeline does not
 * currently generate rules for them.
 *
 * Writes `MISSING_INVERSE_NAMES.md` at the project root and fails the test if
 * any gaps are found.
 *
 * Run with: ./gradlew integrationTest --tests "*.MissingInverseNameDetector"
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = [Application::class])
@EmbeddedKafka(partitions = 1)
@ActiveProfiles("utdanning-vurdering")
@DirtiesContext
class MissingInverseNameDetector {
    @Autowired
    lateinit var metamodelService: MetamodelService

    private data class Gap(
        val sourceClass: String,
        val sourceRelation: String,
        val sourceMultiplicity: FintMultiplicity,
        val targetClass: String,
        val backRefs: List<FintRelation>,
    )

    @Test
    fun `find relation pairs missing inverseName`() {
        val resourcesByClassName: Map<String, Resource> =
            metamodelService.getResources().associateBy { it.className }

        val gaps =
            metamodelService.getResources().flatMap { source ->
                source.relations.mapNotNull { rel -> findGap(source, rel, resourcesByClassName) }
            }

        val report = File("MISSING_INVERSE_NAMES.md")
        if (gaps.isNotEmpty()) {
            report.writeText(buildReport(gaps))
            error("Found ${gaps.size} relation(s) missing inverseName. See ${report.name}")
        } else {
            report.delete()
        }
    }

    private fun findGap(
        source: Resource,
        rel: FintRelation,
        byClassName: Map<String, Resource>,
    ): Gap? {
        val target = byClassName[rel.packageName] ?: return null
        val backRefs = target.relations.filter { it.packageName == source.className }
        if (backRefs.isEmpty()) return null

        // Skip pure 1-to-1: autorelation does not currently support these and the model team
        // does not consistently set inverseName for scalar-to-scalar pairs.
        if (rel.multiplicity.isToOne() && backRefs.all { it.multiplicity.isToOne() }) return null

        if (rel.inverseName != null) return null

        return Gap(
            sourceClass = source.className,
            sourceRelation = rel.name,
            sourceMultiplicity = rel.multiplicity,
            targetClass = target.className,
            backRefs = backRefs,
        )
    }

    private fun buildReport(gaps: List<Gap>): String =
        buildString {
            appendLine("# Missing `inverseName` Report")
            appendLine()
            appendLine(
                "Auto-generated by `MissingInverseNameDetector`. Lists relations where two resources " +
                    "reference each other (via `packageName`) but `inverseName` is null on the source side. " +
                    "Pure 1-to-1 pairs are excluded because the auto-relation pipeline skips them anyway.",
            )
            appendLine()
            appendLine("Total: **${gaps.size}** missing inverse name(s).")
            appendLine()
            appendLine("| Source class | Relation | Multiplicity | → Target class | Back-references on target |")
            appendLine("|---|---|---|---|---|")
            gaps
                .sortedWith(compareBy({ it.sourceClass }, { it.sourceRelation }))
                .forEach { gap ->
                    val backRefs =
                        gap.backRefs.joinToString("<br>") {
                            "`${it.name}` (${it.multiplicity}, inverseName=${it.inverseName ?: "**null**"})"
                        }
                    appendLine(
                        "| `${gap.sourceClass}` " +
                            "| `${gap.sourceRelation}` " +
                            "| ${gap.sourceMultiplicity} " +
                            "| `${gap.targetClass}` " +
                            "| $backRefs |",
                    )
                }
        }

    private fun FintMultiplicity.isToOne() = this == FintMultiplicity.ONE_TO_ONE || this == FintMultiplicity.NONE_TO_ONE
}
