package no.fintlabs.consumer.integration

import no.fintlabs.Application
import no.fintlabs.autorelation.cache.RelationRuleBuilder
import no.fintlabs.autorelation.model.EntityDescriptor
import no.fintlabs.autorelation.model.RelationSyncRule
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.kafka.test.context.EmbeddedKafka
import org.springframework.test.annotation.DirtiesContext
import org.springframework.test.context.TestPropertySource
import java.io.File

/**
 * Generates RELATION_RULES.md at the project root, documenting all auto-relation
 * update rules derived from the FINT metamodel.
 *
 * Run manually with: ./gradlew integrationTest --tests "*.RelationRuleDocGeneratorIT"
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = [Application::class])
@EmbeddedKafka(partitions = 1)
@TestPropertySource(
    properties = [
        "spring.kafka.bootstrap-servers=\${spring.embedded.kafka.brokers}",
        "spring.kafka.consumer.auto-offset-reset=earliest",
        "spring.kafka.consumer.group-id=relation-doc-generator",

        "novari.kafka.default-replicas=1",
        "fint.relation.base-url=https://api.felleskomponent.no",
        "fint.org-id=foo.org",
        "fint.consumer.org-id=foo.org",
        "fint.consumer.domain=utdanning",
        "fint.consumer.package=elev",
        "fint.consumer.autorelation.enabled=true",
        "fint.security.enabled=false",
    ],
)
@DirtiesContext
class RelationRuleDocGenerator {
    @Autowired
    lateinit var ruleBuilder: RelationRuleBuilder

    @Test
    fun `generate RELATION_RULES markdown file`() {
        val allRules: Map<EntityDescriptor, List<RelationSyncRule>> =
            ruleBuilder.buildEntityDescriptorToRules()

        val md =
            buildString {
                appendLine("# Auto-Relation Update Rules")
                appendLine()
                appendLine(
                    "This file is auto-generated by `RelationRuleDocGeneratorIT`. " +
                        "It documents which resources (and relations on them) are updated " +
                        "when a given FINT resource arrives.",
                )
                appendLine()
                appendLine("---")
                appendLine()

                allRules.entries
                    .sortedWith(compareBy({ it.key.domainName }, { it.key.packageName }, { it.key.resourceName }))
                    .forEach { (trigger, rules) ->
                        appendLine("## `${trigger.domainName}-${trigger.packageName}-${trigger.resourceName}`")
                        appendLine()
                        appendLine("When this resource arrives, the following resources are updated:")
                        appendLine()
                        appendLine("| Source Relation | Updated Resource | Back-Relation | Type |")
                        appendLine("|---|---|---|---|")

                        rules.forEach { rule ->
                            val target = rule.targetType
                            val type =
                                when {
                                    rule.isOneToMany() -> "One → Many"
                                    rule.isManyToMany() -> "Many ↔ Many"
                                    else -> "Other"
                                }
                            appendLine(
                                "| `${rule.targetRelation}` " +
                                    "| `${target.domainName}-${target.packageName}-${target.resourceName}` " +
                                    "| `${rule.inverseRelation}` " +
                                    "| $type |",
                            )
                        }

                        appendLine()
                    }
            }

        val outputFile = File("RELATION_RULES.md")
        outputFile.writeText(md)
        println("Generated ${outputFile.absolutePath}")
    }
}
