apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-ressurs-eiendel
  namespace: trondelagfylke-no
spec:
  url:
    hostname: api.felleskomponent.no
  ingress:
    basePaths:
      - /ressurs/eiendel
    headers:
      x-org-id: trondelagfylke.no
  kafka:
    enabled: true
    acls:
      - topic: 'trondelagfylke-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"