apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-personvern-samtykke
  namespace: ffk-no
spec:
  url:
    hostname: alpha.felleskomponent.no
  ingress:
    basePaths:
      - /personvern/samtykke
    headers:
      x-org-id: ffk.no
  kafka:
    enabled: true
    acls:
      - topic: 'ffk-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"