apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-arkiv-personal
  namespace: nfk-no
spec:
  url:
    hostname: api.felleskomponent.no
  ingress:
    basePaths:
      - /arkiv/personal
    headers:
      x-org-id: nfk.no
  kafka:
    enabled: true
    acls:
      - topic: 'nfk-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"