apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-core-consumer
    app.kubernetes.io/instance: fint-core-consumer_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: docker/getting-started
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "1024Mi"
      cpu: "100m"
    requests:
      memory: "128Mi"
      cpu: "100m"