apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer
  namespace: fintlabs-no
spec:
  replicas: 0
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-consumer:latest
  url:
    hostname: replace
  ingress:
    basePaths:
    headers: replace
    enabled: true
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "1024Mi"
      cpu: "1"
    requests:
      memory: "128Mi"
      cpu: "100m"