apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-arkiv-kulturminnevern
  namespace: fintlabs-no
spec:
  url:
    hostname: api.felleskomponent.no
  ingress:
    basePaths:
      - /arkiv/kulturminnevern
    headers:
      x-org-id: fintlabs.no
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "528Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"