name: CD
on:
  release:
    types: [ published ]

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Get resource group name
        uses: actions/github-script@v6
        id: resource-group
        with:
          script: return 'rg-aks-${{ steps.environment.outputs.result }}'
          result-encoding: string

      - name: Check if kustomize path exists
        id: kustomize-check
        run: |
          KUSTOMIZE_PATH="kustomize/overlays/${{ steps.environment.outputs.result }}/${{ matrix.org }}"

          if [ -d "$KUSTOMIZE_PATH" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Found $KUSTOMIZE_PATH"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Skipping $KUSTOMIZE_PATH (does not exist)"
          fi

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}/${{ matrix.org }}'

      - uses: azure/login@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"

      - uses: azure/use-kubelogin@v1.1
        with:
          kubelogin-version: 'v0.0.26'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ matrix.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ matrix.org }}
